services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    command: --ISCAgent false
    restart: always
    ports:
      - 61773:1972
      - 62773:52773
      - 53773
    volumes:
      - ./:/rcc
